### ISSUE TITLE
Setup fails with apache in docker-compose setup

### ISSUE THREAD

**Issue by co60ca** [paragonie/airship#103]
- [ ] Check this box if this is a security vulnerability.

### Summary
Issue during setup, when typing the administrator passwords you will get a 500 error and the screen goes white

### Expected Outcome
Continue to application setup screen

### What Actually Happened
500 error and logs below.

I think it is because we don't have a Cabin/Lens in the master?

### Relevant Debug Information

```
[Thu Jul 07 19:03:19.383320 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Jul 07 19:03:19.383366 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Thu Jul 07 19:16:10.991640 2016] [:error] [pid 11] [client 192.168.2.101:39972] PHP Notice:  Undefined index: twig-vars in /var/www/airship/src/Installer/Install.php on line 445, referer: http://appserv-ub03:8080/
[Thu Jul 07 19:16:10.991681 2016] [:error] [pid 11] [client 192.168.2.101:39972] PHP Notice:  Undefined index: cabin in /var/www/airship/src/Installer/Install.php on line 465, referer: http://appserv-ub03:8080/
[Thu Jul 07 19:16:10.991752 2016] [:error] [pid 11] [client 192.168.2.101:39972] PHP Warning:  Invalid argument supplied for foreach() in /var/www/airship/src/Installer/Install.php on line 542, referer: http://appserv-ub03:8080/
[Thu Jul 07 19:16:10.999476 2016] [:error] [pid 11] [client 192.168.2.101:39972] PHP Notice:  Undefined index: databases in /var/www/airship/src/Installer/Install.php on line 590, referer: http://appserv-ub03:8080/
[Thu Jul 07 19:16:16.419926 2016] [:error] [pid 11] [client 192.168.2.101:39972] PHP Notice:  Undefined index: passphrase in /var/www/airship/src/Installer/Install.php on line 806, referer: http://appserv-ub03:8080/
[Thu Jul 07 19:16:16.479897 2016] [:error] [pid 11] [client 192.168.2.101:39972] PHP Notice:  Undefined index:  in /var/www/airship/src/bootstrap.php on line 31, referer: http://appserv-ub03:8080/
[Thu Jul 07 19:16:16.481611 2016] [:error] [pid 11] [client 192.168.2.101:39972] PHP Fatal error:  Uncaught Twig_Error_Loader: The "/var/www/airship/src/Cabin//Lens" directory does not exist. in /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:94\nStack trace:\n#0 /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(76): Twig_Loader_Filesystem->addPath('/var/www/airshi...', '__main__')\n#1 /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(34): Twig_Loader_Filesystem->setPaths(Array)\n#2 /var/www/airship/src/bootstrap.php(92): Twig_Loader_Filesystem->__construct('/var/www/airshi...')\n#3 /var/www/airship/src/public/index.php(86): require_once('/var/www/airshi...')\n#4 {main}\n  thrown in /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 94, referer: http://appserv-ub03:8080/
```

**Comment by co60ca** [comment]
I'm testing with the current master in Docker fyi

**Comment by co60ca** [comment]
In the docker build I used "database" as the server
airship username
secret password
airship database

Then on the administrator password page I used
airship
and 
airship123456
which showed the poor strength password error then 500'd with this:

```
[Thu Jul 07 20:07:52.815358 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Jul 07 20:07:52.815407 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Thu Jul 07 20:08:16.332445 2016] [:error] [pid 11] [client 192.168.2.101:40834] PHP Notice:  Undefined index: databases in /var/www/airship/src/Installer/Install.php on line 440, referer: http://appserv-ub03:8080/
[Thu Jul 07 20:08:16.332487 2016] [:error] [pid 11] [client 192.168.2.101:40834] PHP Notice:  Undefined index: twig-vars in /var/www/airship/src/Installer/Install.php on line 445, referer: http://appserv-ub03:8080/
[Thu Jul 07 20:08:16.332495 2016] [:error] [pid 11] [client 192.168.2.101:40834] PHP Notice:  Undefined index: cabin in /var/www/airship/src/Installer/Install.php on line 465, referer: http://appserv-ub03:8080/
[Thu Jul 07 20:08:16.332501 2016] [:error] [pid 11] [client 192.168.2.101:40834] PHP Notice:  Undefined index: database in /var/www/airship/src/Installer/Install.php on line 467, referer: http://appserv-ub03:8080/
[Thu Jul 07 20:08:16.332561 2016] [:error] [pid 11] [client 192.168.2.101:40834] PHP Warning:  Invalid argument supplied for foreach() in /var/www/airship/src/Installer/Install.php on line 546, referer: http://appserv-ub03:8080/
[Thu Jul 07 20:08:16.340842 2016] [:error] [pid 11] [client 192.168.2.101:40834] PHP Notice:  Undefined index: databases in /var/www/airship/src/Installer/Install.php on line 594, referer: http://appserv-ub03:8080/
[Thu Jul 07 20:08:16.352795 2016] [:error] [pid 11] [client 192.168.2.101:40834] PHP Fatal error:  Uncaught TypeError: DSN must be string or array in /var/www/airship/src/Engine/Database.php:77\nStack trace:\n#0 /var/www/airship/src/Installer/Install.php(726): Airship\\Engine\\Database::factory(NULL)\n#1 /var/www/airship/src/Installer/Install.php(670): Airship\\Installer\\Install->finalDatabasePrimary()\n#2 /var/www/airship/src/Installer/Install.php(470): Airship\\Installer\\Install->finalDatabaseSetup()\n#3 /var/www/airship/src/Installer/Install.php(131): Airship\\Installer\\Install->finalize(Array)\n#4 /var/www/airship/src/Installer/launch.php(175): Airship\\Installer\\Install->currentStep()\n#5 /var/www/airship/src/public/index.php(26): include('/var/www/airshi...')\n#6 {main}\n  thrown in /var/www/airship/src/Engine/Database.php on line 77, referer: http://appserv-ub03:8080/
```

**Comment by co60ca** [comment]
This issue is closed, new one is different
