### ISSUE TITLE
Editing pages not possible

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#118]
### Summary

Editing pages isn't possible and results in an internal error. I setup Airship via Docker with default settings and tried to edit one of the pre-existing pages.

### Expected Outcome

Edit form for the selected page.

### What Actually Happened

```
<br />
<b>Notice</b>:  Undefined index: page in <b>/var/www/airship/src/Cabin/Bridge/Landing/PageManager.php</b> on line <b>225</b><br />
DEBUG ERROR: TypeError

Argument 3 passed to Airship\Cabin\Bridge\Blueprint\CustomPages::getPageInfo() must be of the type string, null given, called in /var/www/airship/src/Cabin/Bridge/Landing/PageManager.php on line 225

0

#0 /var/www/airship/src/Cabin/Bridge/Landing/PageManager.php(225): Airship\Cabin\Bridge\Blueprint\CustomPages->getPageInfo('Hull', '', NULL)
#1 /var/www/airship/src/Engine/AutoPilot.php(429): Airship\Cabin\Bridge\Landing\PageManager->editPage('Hull')
#2 /var/www/airship/src/Engine/AutoPilot.php(264): Airship\Engine\AutoPilot->serve(Array, Array)
#3 /var/www/airship/src/public/index.php(156): Airship\Engine\AutoPilot->route()
#4 {main}<!-- Load time: 0.55504 s -->
```

**Comment by paragonie-scott** [comment]
This might be another issue in the "Apache configuration doesn't pass GET parameters when using rewrite" category.

**Comment by kelunik** [comment]
Closing as #121 is merged.
