### ISSUE TITLE
No error recovery in install process for bad database credentials

### ISSUE THREAD

**Issue by co60ca** [paragonie/airship#47]
- [ ] Check this box if this is a security vulnerability.

### Summary
If you fail to use the correct username&password for your database you just get a blank screen at the end of the install process due to a 500 server error

### Expected Outcome
Failure in UI shown, potentially bounce back to the database configuration screen 

### What Actually Happened
Blank screen shown due to 500 server error
Password shown in error.log logs, unsure if this is considered privileged?

```
[Tue Jun 28 01:43:52.244561 2016] [:error] [pid 15927] [client 192.168.2.146:39360] PHP Notice:  Undefined index: databases in /var/www/html/airship/src/Installer/Install.php on line 414, referer: http://appserv-ub03/
[Tue Jun 28 01:43:52.264859 2016] [:error] [pid 15927] [client 192.168.2.146:39360] PHP Fatal error:  Uncaught Airship\\Alerts\\Database\\DBException: Could not create a database connection. Please check your username and password. in /var/www/html/airship/src/Engine/Database.php:95\nStack trace:\n#0 /var/www/html/airship/src/Installer/Install.php(534): Airship\\Engine\\Database::factory('pgsql:host=loca...', 'postgres', 'secret...', Array)\n#1 /var/www/html/airship/src/Installer/Install.php(478): Airship\\Installer\\Install->finalDatabasePrimary()\n#2 /var/www/html/airship/src/Installer/Install.php(294): Airship\\Installer\\Install->finalDatabaseSetup()\n#3 /var/www/html/airship/src/Installer/Install.php(132): Airship\\Installer\\Install->finalize(Array)\n#4 /var/www/html/airship/src/Installer/launch.php(171): Airship\\Installer\\Install->currentStep()\n#5 /var/www/html/airship/src/public/index.php(26): include('/var/www/html/a...')\n#6 {main}\n  thrown in /var/www/html/airship/src/Engine/Database.php on line 95, referer: http://appserv-ub03/
```

**Comment by paragonie-scott** [comment]
Ah, good catch. That should definitely be fixed.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/913889307ba80b134f64415977cb56894c2fbb86

That *should* fix it.

**Comment by paragonie-scott** [comment]
This is fixed in `master`. It will land in `1.1.0` tomorrow.
