### ISSUE TITLE
2FA setup page is a blank white page

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#66]
### Expected Outcome

A setup page.

### What Actually Happened

http://localhost:8001/bridge/my/account/2-factor is a blank white page (error 500).

**Comment by paragonie-scott** [comment]
Interesting. Can you turn debug mode on (Administrative > Airship Settings) and tell me what error messages you see, if any?

**Comment by kelunik** [comment]
```
DEBUG ERROR: TypeError

Argument 2 passed to ParagonIE\MultiFactor\OTP\TOTP::__construct() must be of the type integer, string given, called in /var/www/airship/src/Cabin/Bridge/Landing/Account.php on line 880

0

#0 /var/www/airship/src/Cabin/Bridge/Landing/Account.php(880): ParagonIE\MultiFactor\OTP\TOTP->__construct(0, '30', '6')
#1 /var/www/airship/src/Cabin/Bridge/Landing/Account.php(323): Airship\Cabin\Bridge\Landing\Account->twoFactorPreamble()
#2 /var/www/airship/src/Engine/AutoPilot.php(429): Airship\Cabin\Bridge\Landing\Account->twoFactorSetup()
#3 /var/www/airship/src/Engine/AutoPilot.php(264): Airship\Engine\AutoPilot->serve(Array, Array)
#4 /var/www/airship/src/public/index.php(152): Airship\Engine\AutoPilot->route()
#5 {main}<!-- Load time: 0.32855 s -->
```

**Comment by paragonie-scott** [comment]
I'm appalled that my testing didn't catch this. Will fix ASAP.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/900dcd8eeb9c41eaa28a50d423f25300c9b45b49 - will release v1.1.1 with fixes soon.
