### ISSUE TITLE
2FA setup QR code broken

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#80]
The QR code doesn't load due to a error 500 in http://localhost:8001/bridge/my/account/2-factor/qr-code

```
DEBUG ERROR: Error

Call to undefined function BaconQrCode\Renderer\Image\imagecreatetruecolor()

0

#0 /var/www/airship/vendor/bacon/bacon-qr-code/src/BaconQrCode/Renderer/Image/AbstractRenderer.php(299): BaconQrCode\Renderer\Image\Png->init()
#1 /var/www/airship/vendor/bacon/bacon-qr-code/src/BaconQrCode/Writer.php(84): BaconQrCode\Renderer\Image\AbstractRenderer->render(Object(BaconQrCode\Encoder\QrCode))
#2 /var/www/airship/vendor/bacon/bacon-qr-code/src/BaconQrCode/Writer.php(103): BaconQrCode\Writer->writeString('otpauth://totp/...', 'ISO-8859-1', 1)
#3 /var/www/airship/vendor/paragonie/multi-factor/src/Vendor/GoogleAuth.php(86): BaconQrCode\Writer->writeFile('otpauth://totp/...', 'php://output')
#4 /var/www/airship/src/Cabin/Bridge/Landing/Account.php(311): ParagonIE\MultiFactor\Vendor\GoogleAuth->makeQRCode(Object(BaconQrCode\Writer), 'php://output', 'test@localhost:...', '', '')
#5 /var/www/airship/src/Engine/AutoPilot.php(429): Airship\Cabin\Bridge\Landing\Account->twoFactorSetupQRCode()
#6 /var/www/airship/src/Engine/AutoPilot.php(264): Airship\Engine\AutoPilot->serve(Array, Array)
#7 /var/www/airship/src/public/index.php(152): Airship\Engine\AutoPilot->route()
#8 {main}<!-- Load time: 0.31713 s -->
```

**Comment by paragonie-scott** [comment]
It appears I added `ext-gd` to the documentation but *not* to `composer.json`.

**Comment by kelunik** [comment]
It's also missing in the Dockerfile then.

**Comment by paragonie-scott** [comment]
As a second layer of mitigation, I've set it to default to SVG (which doesn't require the GD extension) if said extension is not available. https://github.com/paragonie/airship/commit/05aa978f43914fcc8a013f048a25978cf4adcecc
